# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 5
      include:
        - "*"
  - package-ecosystem: gomod
    directory: cloudwatch-logs-aggregator/lambda
    schedule:
      interval: daily
    cooldown:
      default-days: 5
      include:
        - "*"
      exclude:
        - "github.com/mackerelio/*"
        - "github.com/aws/aws-lambda-go"
        - "github.com/aws/aws-sdk-go-v2"
        - "github.com/aws/aws-sdk-go-v2/*"
    groups:
      aws/aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2"
          - "github.com/aws/aws-sdk-go-v2/*"
